### ISSUE TITLE
Fix translation of public/src/client/topic/events.ts

### ISSUE THREAD

**Issue by liam-gersten** [CMU-313/spring23-nodebb-team-hecl-io#64]
The file's translation used another team's translation as reference. This included a blanket /* eslint-disable*/ disable line as a placeholder to disable the linter. This file must now be properly translated to typescript, and pass the linter.

**Comment by cmay20** [comment]
JUSTIFICATION FOR INCOMPLETE STATUS - SPRINT 2:

We did not have enough time to complete this entire translation successfully for Sprint 2. This is because we had many other files that we had to translate for our new NodeBB features. These took more time than we originally estimated. Hence, there was not enough time to complete this issue for Sprint 2. We will push this issue to a future sprint.
